version: "3.0"

services:
    pbs-back:
        image: "politosftengteam6/pulsebs:backv0.4"
        build: "./server"
        network_mode: "bridge"
        links:
            - "mailserver"
        depends_on:
            - "mailserver"
    pbs-front:
        image: "politosftengteam6/pulsebs:frontv0.4"
        build: "./client"
        network_mode: "bridge"
        ports:
            - "3000:3000"
        expose:
            - "3000"
        links:
            - "pbs-back"
        depends_on:
            - "pbs-back"
    mailserver:
        image: "mailhog/mailhog"
        network_mode: "bridge"
        ports:
            - "8025:8025"
        expose:
            - "8025"
        environment:
            - MH_AUTH_FILE=/etc/authfile
            - MH_HOSTNAME=mailserver
        volumes:
            - ./server/authfile:/etc/authfile
